/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 77
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_nextflow_process = 2,
  anon_sym_nextflow_workflow = 3,
  anon_sym_nextflow_pipeline = 4,
  anon_sym_nextflow_function = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_setup = 8,
  anon_sym_run = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_alias = 12,
  anon_sym_COLON = 13,
  anon_sym_RPAREN = 14,
  anon_sym_test = 15,
  anon_sym_when = 16,
  anon_sym_params = 17,
  anon_sym_then = 18,
  anon_sym_tag = 19,
  anon_sym_script = 20,
  anon_sym_options = 21,
  anon_sym_config = 22,
  anon_sym_name = 23,
  anon_sym_profile = 24,
  sym_groovy_code = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_double_string_token1 = 27,
  anon_sym_SQUOTE = 28,
  aux_sym_single_string_token1 = 29,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 30,
  aux_sym_groovy_triple_string_token1 = 31,
  sym_escape_sequence = 32,
  anon_sym_process = 33,
  anon_sym_workflow = 34,
  anon_sym_function = 35,
  sym_line_comment = 36,
  sym_block_comment = 37,
  sym_source_file = 38,
  sym_suite = 39,
  sym_suite_block = 40,
  sym_setup_block = 41,
  sym_run_block = 42,
  sym_run_header = 43,
  sym_test_block = 44,
  sym_test_header = 45,
  sym_when_block = 46,
  sym_params_block = 47,
  sym_then_block = 48,
  sym_invocation = 49,
  sym_top_level_declaration = 50,
  sym_tag_stmt = 51,
  sym_script_stmt = 52,
  sym_options_stmt = 53,
  sym_config_stmt = 54,
  sym_unit_stmt = 55,
  sym_name_stmt = 56,
  sym_profile_stmt = 57,
  sym_groovy_block = 58,
  sym_brace_block = 59,
  sym_string = 60,
  sym_double_string = 61,
  sym_single_string = 62,
  sym_groovy_triple_string = 63,
  sym_quoted_identifier = 64,
  sym_double_quoted_identifier = 65,
  sym_single_quoted_identifier = 66,
  sym_invocable_unit = 67,
  aux_sym_suite_block_repeat1 = 68,
  aux_sym_suite_block_repeat2 = 69,
  aux_sym_setup_block_repeat1 = 70,
  aux_sym_run_block_repeat1 = 71,
  aux_sym_test_block_repeat1 = 72,
  aux_sym_groovy_block_repeat1 = 73,
  aux_sym_double_string_repeat1 = 74,
  aux_sym_single_string_repeat1 = 75,
  aux_sym_groovy_triple_string_repeat1 = 76,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_nextflow_process] = "nextflow_process",
  [anon_sym_nextflow_workflow] = "nextflow_workflow",
  [anon_sym_nextflow_pipeline] = "nextflow_pipeline",
  [anon_sym_nextflow_function] = "nextflow_function",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_setup] = "setup",
  [anon_sym_run] = "run",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_alias] = "alias",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_test] = "test",
  [anon_sym_when] = "when",
  [anon_sym_params] = "params",
  [anon_sym_then] = "then",
  [anon_sym_tag] = "tag",
  [anon_sym_script] = "script",
  [anon_sym_options] = "options",
  [anon_sym_config] = "config",
  [anon_sym_name] = "name",
  [anon_sym_profile] = "profile",
  [sym_groovy_code] = "groovy_code",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_string_token1] = "double_string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_string_token1] = "single_string_token1",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [aux_sym_groovy_triple_string_token1] = "groovy_triple_string_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_process] = "process",
  [anon_sym_workflow] = "workflow",
  [anon_sym_function] = "function",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_suite] = "suite",
  [sym_suite_block] = "suite_block",
  [sym_setup_block] = "setup_block",
  [sym_run_block] = "run_block",
  [sym_run_header] = "run_header",
  [sym_test_block] = "test_block",
  [sym_test_header] = "test_header",
  [sym_when_block] = "when_block",
  [sym_params_block] = "params_block",
  [sym_then_block] = "then_block",
  [sym_invocation] = "invocation",
  [sym_top_level_declaration] = "top_level_declaration",
  [sym_tag_stmt] = "tag_stmt",
  [sym_script_stmt] = "script_stmt",
  [sym_options_stmt] = "options_stmt",
  [sym_config_stmt] = "config_stmt",
  [sym_unit_stmt] = "unit_stmt",
  [sym_name_stmt] = "name_stmt",
  [sym_profile_stmt] = "profile_stmt",
  [sym_groovy_block] = "groovy_block",
  [sym_brace_block] = "brace_block",
  [sym_string] = "string",
  [sym_double_string] = "double_string",
  [sym_single_string] = "single_string",
  [sym_groovy_triple_string] = "groovy_triple_string",
  [sym_quoted_identifier] = "quoted_identifier",
  [sym_double_quoted_identifier] = "double_quoted_identifier",
  [sym_single_quoted_identifier] = "single_quoted_identifier",
  [sym_invocable_unit] = "invocable_unit",
  [aux_sym_suite_block_repeat1] = "suite_block_repeat1",
  [aux_sym_suite_block_repeat2] = "suite_block_repeat2",
  [aux_sym_setup_block_repeat1] = "setup_block_repeat1",
  [aux_sym_run_block_repeat1] = "run_block_repeat1",
  [aux_sym_test_block_repeat1] = "test_block_repeat1",
  [aux_sym_groovy_block_repeat1] = "groovy_block_repeat1",
  [aux_sym_double_string_repeat1] = "double_string_repeat1",
  [aux_sym_single_string_repeat1] = "single_string_repeat1",
  [aux_sym_groovy_triple_string_repeat1] = "groovy_triple_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_nextflow_process] = anon_sym_nextflow_process,
  [anon_sym_nextflow_workflow] = anon_sym_nextflow_workflow,
  [anon_sym_nextflow_pipeline] = anon_sym_nextflow_pipeline,
  [anon_sym_nextflow_function] = anon_sym_nextflow_function,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_setup] = anon_sym_setup,
  [anon_sym_run] = anon_sym_run,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_test] = anon_sym_test,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_params] = anon_sym_params,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_tag] = anon_sym_tag,
  [anon_sym_script] = anon_sym_script,
  [anon_sym_options] = anon_sym_options,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_name] = anon_sym_name,
  [anon_sym_profile] = anon_sym_profile,
  [sym_groovy_code] = sym_groovy_code,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_string_token1] = aux_sym_double_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_string_token1] = aux_sym_single_string_token1,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [aux_sym_groovy_triple_string_token1] = aux_sym_groovy_triple_string_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_process] = anon_sym_process,
  [anon_sym_workflow] = anon_sym_workflow,
  [anon_sym_function] = anon_sym_function,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_suite] = sym_suite,
  [sym_suite_block] = sym_suite_block,
  [sym_setup_block] = sym_setup_block,
  [sym_run_block] = sym_run_block,
  [sym_run_header] = sym_run_header,
  [sym_test_block] = sym_test_block,
  [sym_test_header] = sym_test_header,
  [sym_when_block] = sym_when_block,
  [sym_params_block] = sym_params_block,
  [sym_then_block] = sym_then_block,
  [sym_invocation] = sym_invocation,
  [sym_top_level_declaration] = sym_top_level_declaration,
  [sym_tag_stmt] = sym_tag_stmt,
  [sym_script_stmt] = sym_script_stmt,
  [sym_options_stmt] = sym_options_stmt,
  [sym_config_stmt] = sym_config_stmt,
  [sym_unit_stmt] = sym_unit_stmt,
  [sym_name_stmt] = sym_name_stmt,
  [sym_profile_stmt] = sym_profile_stmt,
  [sym_groovy_block] = sym_groovy_block,
  [sym_brace_block] = sym_brace_block,
  [sym_string] = sym_string,
  [sym_double_string] = sym_double_string,
  [sym_single_string] = sym_single_string,
  [sym_groovy_triple_string] = sym_groovy_triple_string,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [sym_double_quoted_identifier] = sym_double_quoted_identifier,
  [sym_single_quoted_identifier] = sym_single_quoted_identifier,
  [sym_invocable_unit] = sym_invocable_unit,
  [aux_sym_suite_block_repeat1] = aux_sym_suite_block_repeat1,
  [aux_sym_suite_block_repeat2] = aux_sym_suite_block_repeat2,
  [aux_sym_setup_block_repeat1] = aux_sym_setup_block_repeat1,
  [aux_sym_run_block_repeat1] = aux_sym_run_block_repeat1,
  [aux_sym_test_block_repeat1] = aux_sym_test_block_repeat1,
  [aux_sym_groovy_block_repeat1] = aux_sym_groovy_block_repeat1,
  [aux_sym_double_string_repeat1] = aux_sym_double_string_repeat1,
  [aux_sym_single_string_repeat1] = aux_sym_single_string_repeat1,
  [aux_sym_groovy_triple_string_repeat1] = aux_sym_groovy_triple_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_nextflow_process] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nextflow_workflow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nextflow_pipeline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nextflow_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_setup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_run] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_test] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_params] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_script] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_options] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_name] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_profile] = {
    .visible = true,
    .named = false,
  },
  [sym_groovy_code] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_groovy_triple_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_process] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_workflow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_suite] = {
    .visible = true,
    .named = true,
  },
  [sym_suite_block] = {
    .visible = true,
    .named = true,
  },
  [sym_setup_block] = {
    .visible = true,
    .named = true,
  },
  [sym_run_block] = {
    .visible = true,
    .named = true,
  },
  [sym_run_header] = {
    .visible = true,
    .named = true,
  },
  [sym_test_block] = {
    .visible = true,
    .named = true,
  },
  [sym_test_header] = {
    .visible = true,
    .named = true,
  },
  [sym_when_block] = {
    .visible = true,
    .named = true,
  },
  [sym_params_block] = {
    .visible = true,
    .named = true,
  },
  [sym_then_block] = {
    .visible = true,
    .named = true,
  },
  [sym_invocation] = {
    .visible = true,
    .named = true,
  },
  [sym_top_level_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_script_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_options_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_config_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_name_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_profile_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_groovy_block] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_string] = {
    .visible = true,
    .named = true,
  },
  [sym_groovy_triple_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_invocable_unit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_suite_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_suite_block_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setup_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_run_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_test_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_groovy_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_groovy_triple_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_body = 2,
  field_groovy = 3,
  field_identifier = 4,
  field_name = 5,
  field_type = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_body] = "body",
  [field_groovy] = "groovy",
  [field_identifier] = "identifier",
  [field_name] = "name",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 1},
  [8] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_value, 1},
  [2] =
    {field_name, 2},
  [3] =
    {field_identifier, 1},
  [4] =
    {field_identifier, 2},
  [5] =
    {field_groovy, 1},
  [6] =
    {field_type, 0},
  [7] =
    {field_alias, 6},
    {field_identifier, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 9,
  [64] = 5,
  [65] = 6,
  [66] = 7,
  [67] = 8,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 71,
  [78] = 78,
  [79] = 75,
  [80] = 73,
  [81] = 68,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 27,
        '\'', 29,
        '(', 17,
        ')', 20,
        ',', 18,
        '/', 10,
        ':', 19,
        '\\', 13,
        '{', 15,
        '}', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(9);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '}') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '/') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead == '\\') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == '*') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(38);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '*') ADVANCE(23);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(12);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '/') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_double_string_token1);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_single_string_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_groovy_triple_string_token1);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_groovy_triple_string_token1);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '/') ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_groovy_triple_string_token1);
      if (lookahead == '"') ADVANCE(7);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_groovy_triple_string_token1);
      if (lookahead == '*') ADVANCE(12);
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'c', 2,
        'f', 3,
        'n', 4,
        'o', 5,
        'p', 6,
        'r', 7,
        's', 8,
        't', 9,
        'w', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'x') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 'f') ADVANCE(51);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_run);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_tag);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 42:
      if (lookahead == 'k') ADVANCE(57);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_name);
      END_STATE();
    case 47:
      if (lookahead == 'f') ADVANCE(61);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(63);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 53:
      if (lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_test);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 57:
      if (lookahead == 'f') ADVANCE(68);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 59:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(72);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_setup);
      END_STATE();
    case 68:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_config);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(78);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 72:
      if (lookahead == 's') ADVANCE(80);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_params);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(81);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_script);
      END_STATE();
    case 77:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 79:
      if (lookahead == 'w') ADVANCE(85);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_options);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_process);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_profile);
      END_STATE();
    case 83:
      if (lookahead == 'w') ADVANCE(86);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 85:
      if (lookahead == '_') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_workflow);
      END_STATE();
    case 87:
      if (lookahead == 'f') ADVANCE(88);
      if (lookahead == 'p') ADVANCE(89);
      if (lookahead == 'w') ADVANCE(90);
      END_STATE();
    case 88:
      if (lookahead == 'u') ADVANCE(91);
      END_STATE();
    case 89:
      if (lookahead == 'i') ADVANCE(92);
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 90:
      if (lookahead == 'o') ADVANCE(94);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 92:
      if (lookahead == 'p') ADVANCE(96);
      END_STATE();
    case 93:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 94:
      if (lookahead == 'r') ADVANCE(98);
      END_STATE();
    case 95:
      if (lookahead == 'c') ADVANCE(99);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 97:
      if (lookahead == 'c') ADVANCE(101);
      END_STATE();
    case 98:
      if (lookahead == 'k') ADVANCE(102);
      END_STATE();
    case 99:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 100:
      if (lookahead == 'l') ADVANCE(104);
      END_STATE();
    case 101:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 102:
      if (lookahead == 'f') ADVANCE(106);
      END_STATE();
    case 103:
      if (lookahead == 'i') ADVANCE(107);
      END_STATE();
    case 104:
      if (lookahead == 'i') ADVANCE(108);
      END_STATE();
    case 105:
      if (lookahead == 's') ADVANCE(109);
      END_STATE();
    case 106:
      if (lookahead == 'l') ADVANCE(110);
      END_STATE();
    case 107:
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 108:
      if (lookahead == 'n') ADVANCE(112);
      END_STATE();
    case 109:
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 110:
      if (lookahead == 'o') ADVANCE(114);
      END_STATE();
    case 111:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 112:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_nextflow_process);
      END_STATE();
    case 114:
      if (lookahead == 'w') ADVANCE(117);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_nextflow_function);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_nextflow_pipeline);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_nextflow_workflow);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 8},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_nextflow_process] = ACTIONS(1),
    [anon_sym_nextflow_workflow] = ACTIONS(1),
    [anon_sym_nextflow_pipeline] = ACTIONS(1),
    [anon_sym_nextflow_function] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_setup] = ACTIONS(1),
    [anon_sym_run] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_test] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_params] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_tag] = ACTIONS(1),
    [anon_sym_script] = ACTIONS(1),
    [anon_sym_options] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_name] = ACTIONS(1),
    [anon_sym_profile] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_process] = ACTIONS(1),
    [anon_sym_workflow] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(97),
    [sym_suite] = STATE(94),
    [anon_sym_nextflow_process] = ACTIONS(5),
    [anon_sym_nextflow_workflow] = ACTIONS(5),
    [anon_sym_nextflow_pipeline] = ACTIONS(5),
    [anon_sym_nextflow_function] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(15), 1,
      anon_sym_script,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(21), 1,
      anon_sym_name,
    ACTIONS(23), 1,
      anon_sym_profile,
    STATE(47), 1,
      sym_setup_block,
    STATE(50), 1,
      sym_invocable_unit,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 2,
      sym_top_level_declaration,
      aux_sym_suite_block_repeat1,
    STATE(52), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(21), 7,
      sym_tag_stmt,
      sym_script_stmt,
      sym_options_stmt,
      sym_config_stmt,
      sym_unit_stmt,
      sym_name_stmt,
      sym_profile_stmt,
  [63] = 17,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(15), 1,
      anon_sym_script,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(21), 1,
      anon_sym_name,
    ACTIONS(23), 1,
      anon_sym_profile,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(50), 1,
      sym_invocable_unit,
    STATE(53), 1,
      sym_setup_block,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 2,
      sym_top_level_declaration,
      aux_sym_suite_block_repeat1,
    STATE(49), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(21), 7,
      sym_tag_stmt,
      sym_script_stmt,
      sym_options_stmt,
      sym_config_stmt,
      sym_unit_stmt,
      sym_name_stmt,
      sym_profile_stmt,
  [126] = 12,
    ACTIONS(31), 1,
      anon_sym_tag,
    ACTIONS(34), 1,
      anon_sym_script,
    ACTIONS(37), 1,
      anon_sym_options,
    ACTIONS(40), 1,
      anon_sym_config,
    ACTIONS(43), 1,
      anon_sym_name,
    ACTIONS(46), 1,
      anon_sym_profile,
    STATE(50), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 2,
      sym_top_level_declaration,
      aux_sym_suite_block_repeat1,
    ACTIONS(29), 3,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
    ACTIONS(49), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(21), 7,
      sym_tag_stmt,
      sym_script_stmt,
      sym_options_stmt,
      sym_config_stmt,
      sym_unit_stmt,
      sym_name_stmt,
      sym_profile_stmt,
  [175] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(52), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [197] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(54), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [219] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(56), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [241] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(58), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [263] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(60), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [285] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(62), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [306] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(64), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [327] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(66), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [348] = 9,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(70), 1,
      anon_sym_when,
    ACTIONS(72), 1,
      anon_sym_then,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(14), 7,
      sym_setup_block,
      sym_when_block,
      sym_then_block,
      sym_tag_stmt,
      sym_options_stmt,
      sym_config_stmt,
      aux_sym_test_block_repeat1,
  [383] = 9,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(70), 1,
      anon_sym_when,
    ACTIONS(72), 1,
      anon_sym_then,
    ACTIONS(74), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(17), 7,
      sym_setup_block,
      sym_when_block,
      sym_then_block,
      sym_tag_stmt,
      sym_options_stmt,
      sym_config_stmt,
      aux_sym_test_block_repeat1,
  [418] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(76), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [439] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(78), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [460] = 9,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 1,
      anon_sym_setup,
    ACTIONS(85), 1,
      anon_sym_when,
    ACTIONS(88), 1,
      anon_sym_then,
    ACTIONS(91), 1,
      anon_sym_tag,
    ACTIONS(94), 1,
      anon_sym_options,
    ACTIONS(97), 1,
      anon_sym_config,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(17), 7,
      sym_setup_block,
      sym_when_block,
      sym_then_block,
      sym_tag_stmt,
      sym_options_stmt,
      sym_config_stmt,
      aux_sym_test_block_repeat1,
  [495] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [516] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(102), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [535] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(104), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [554] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(106), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [573] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [592] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(110), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [611] = 7,
    ACTIONS(15), 1,
      anon_sym_script,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(112), 1,
      anon_sym_RBRACE,
    STATE(105), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(25), 4,
      sym_invocation,
      sym_script_stmt,
      sym_config_stmt,
      aux_sym_run_block_repeat1,
  [639] = 7,
    ACTIONS(15), 1,
      anon_sym_script,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(105), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(26), 4,
      sym_invocation,
      sym_script_stmt,
      sym_config_stmt,
      aux_sym_run_block_repeat1,
  [667] = 7,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    ACTIONS(118), 1,
      anon_sym_script,
    ACTIONS(121), 1,
      anon_sym_config,
    STATE(105), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(124), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(26), 4,
      sym_invocation,
      sym_script_stmt,
      sym_config_stmt,
      aux_sym_run_block_repeat1,
  [695] = 8,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 1,
      sym_groovy_code,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      anon_sym_SQUOTE,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(63), 2,
      sym_double_string,
      sym_single_string,
    STATE(29), 3,
      sym_brace_block,
      sym_string,
      aux_sym_groovy_block_repeat1,
  [724] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(139), 10,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [741] = 8,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      anon_sym_SQUOTE,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    ACTIONS(143), 1,
      sym_groovy_code,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(63), 2,
      sym_double_string,
      sym_single_string,
    STATE(33), 3,
      sym_brace_block,
      sym_string,
      aux_sym_groovy_block_repeat1,
  [770] = 8,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      anon_sym_SQUOTE,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    ACTIONS(147), 1,
      sym_groovy_code,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(63), 2,
      sym_double_string,
      sym_single_string,
    STATE(31), 3,
      sym_brace_block,
      sym_string,
      aux_sym_groovy_block_repeat1,
  [799] = 8,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      anon_sym_SQUOTE,
    ACTIONS(143), 1,
      sym_groovy_code,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(63), 2,
      sym_double_string,
      sym_single_string,
    STATE(33), 3,
      sym_brace_block,
      sym_string,
      aux_sym_groovy_block_repeat1,
  [828] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(151), 10,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [845] = 8,
    ACTIONS(153), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_RBRACE,
    ACTIONS(158), 1,
      sym_groovy_code,
    ACTIONS(161), 1,
      anon_sym_DQUOTE,
    ACTIONS(164), 1,
      anon_sym_SQUOTE,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(63), 2,
      sym_double_string,
      sym_single_string,
    STATE(33), 3,
      sym_brace_block,
      sym_string,
      aux_sym_groovy_block_repeat1,
  [874] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(167), 8,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [889] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(169), 8,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [904] = 6,
    ACTIONS(171), 1,
      anon_sym_params,
    STATE(41), 1,
      sym_params_block,
    STATE(83), 1,
      sym_invocation,
    STATE(105), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [926] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(173), 7,
      anon_sym_RBRACE,
      anon_sym_params,
      anon_sym_script,
      anon_sym_config,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [940] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(175), 7,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [954] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(177), 7,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [968] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(179), 7,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [982] = 5,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_invocation,
    STATE(105), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [1001] = 5,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 1,
      anon_sym_run,
    STATE(111), 1,
      sym_run_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(58), 2,
      sym_run_block,
      aux_sym_setup_block_repeat1,
  [1019] = 5,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(11), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_double_string,
      sym_single_string,
  [1037] = 5,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(20), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_double_string,
      sym_single_string,
  [1055] = 5,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    ACTIONS(193), 1,
      anon_sym_run,
    STATE(111), 1,
      sym_run_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(45), 2,
      sym_run_block,
      aux_sym_setup_block_repeat1,
  [1073] = 5,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(23), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_double_string,
      sym_single_string,
  [1091] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(49), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1109] = 5,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(15), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_double_string,
      sym_single_string,
  [1127] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(54), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1145] = 5,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    ACTIONS(200), 1,
      anon_sym_SQUOTE,
    STATE(19), 1,
      sym_quoted_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(12), 2,
      sym_double_quoted_identifier,
      sym_single_quoted_identifier,
  [1163] = 5,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(22), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_double_string,
      sym_single_string,
  [1181] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(54), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1199] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(59), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1217] = 5,
    ACTIONS(202), 1,
      anon_sym_RBRACE,
    ACTIONS(204), 1,
      anon_sym_test,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(54), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1235] = 5,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(114), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_double_string,
      sym_single_string,
  [1253] = 5,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(10), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(9), 2,
      sym_double_string,
      sym_single_string,
  [1271] = 2,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(207), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1283] = 5,
    ACTIONS(185), 1,
      anon_sym_run,
    ACTIONS(209), 1,
      anon_sym_RBRACE,
    STATE(111), 1,
      sym_run_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(45), 2,
      sym_run_block,
      aux_sym_setup_block_repeat1,
  [1301] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    STATE(98), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(54), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1319] = 2,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(213), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1331] = 5,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    ACTIONS(200), 1,
      anon_sym_SQUOTE,
    STATE(109), 1,
      sym_quoted_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(12), 2,
      sym_double_quoted_identifier,
      sym_single_quoted_identifier,
  [1349] = 5,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    ACTIONS(200), 1,
      anon_sym_SQUOTE,
    STATE(84), 1,
      sym_quoted_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(12), 2,
      sym_double_quoted_identifier,
      sym_single_quoted_identifier,
  [1367] = 2,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(215), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1379] = 2,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(217), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1391] = 2,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(219), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1403] = 2,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(221), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1415] = 2,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(223), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1427] = 5,
    ACTIONS(225), 1,
      anon_sym_SQUOTE,
    ACTIONS(227), 1,
      aux_sym_single_string_token1,
    ACTIONS(229), 1,
      sym_escape_sequence,
    STATE(78), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1444] = 5,
    ACTIONS(231), 1,
      anon_sym_DQUOTE,
    ACTIONS(233), 1,
      aux_sym_double_string_token1,
    ACTIONS(236), 1,
      sym_escape_sequence,
    STATE(69), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1461] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(239), 4,
      anon_sym_RBRACE,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [1472] = 5,
    ACTIONS(241), 1,
      anon_sym_DQUOTE,
    ACTIONS(243), 1,
      aux_sym_double_string_token1,
    ACTIONS(245), 1,
      sym_escape_sequence,
    STATE(73), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1489] = 4,
    ACTIONS(247), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(74), 1,
      aux_sym_groovy_triple_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(249), 2,
      aux_sym_groovy_triple_string_token1,
      sym_escape_sequence,
  [1504] = 5,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
    ACTIONS(253), 1,
      aux_sym_double_string_token1,
    ACTIONS(255), 1,
      sym_escape_sequence,
    STATE(69), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1521] = 4,
    ACTIONS(257), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(76), 1,
      aux_sym_groovy_triple_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(259), 2,
      aux_sym_groovy_triple_string_token1,
      sym_escape_sequence,
  [1536] = 5,
    ACTIONS(261), 1,
      anon_sym_SQUOTE,
    ACTIONS(263), 1,
      aux_sym_single_string_token1,
    ACTIONS(265), 1,
      sym_escape_sequence,
    STATE(68), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1553] = 4,
    ACTIONS(267), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(76), 1,
      aux_sym_groovy_triple_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(269), 2,
      aux_sym_groovy_triple_string_token1,
      sym_escape_sequence,
  [1568] = 5,
    ACTIONS(272), 1,
      anon_sym_DQUOTE,
    ACTIONS(274), 1,
      aux_sym_double_string_token1,
    ACTIONS(276), 1,
      sym_escape_sequence,
    STATE(80), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1585] = 5,
    ACTIONS(278), 1,
      anon_sym_SQUOTE,
    ACTIONS(280), 1,
      aux_sym_single_string_token1,
    ACTIONS(283), 1,
      sym_escape_sequence,
    STATE(78), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1602] = 5,
    ACTIONS(286), 1,
      anon_sym_SQUOTE,
    ACTIONS(288), 1,
      aux_sym_single_string_token1,
    ACTIONS(290), 1,
      sym_escape_sequence,
    STATE(81), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1619] = 5,
    ACTIONS(253), 1,
      aux_sym_double_string_token1,
    ACTIONS(255), 1,
      sym_escape_sequence,
    ACTIONS(292), 1,
      anon_sym_DQUOTE,
    STATE(69), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1636] = 5,
    ACTIONS(227), 1,
      aux_sym_single_string_token1,
    ACTIONS(229), 1,
      sym_escape_sequence,
    ACTIONS(294), 1,
      anon_sym_SQUOTE,
    STATE(78), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(137), 2,
      sym_line_comment,
      sym_block_comment,
  [1653] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(296), 3,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1663] = 4,
    ACTIONS(171), 1,
      anon_sym_params,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(95), 1,
      sym_params_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1677] = 3,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1688] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(302), 2,
      anon_sym_RBRACE,
      anon_sym_run,
  [1697] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(304), 2,
      anon_sym_RBRACE,
      anon_sym_test,
  [1706] = 3,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    STATE(70), 1,
      sym_groovy_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1717] = 3,
    ACTIONS(306), 1,
      anon_sym_LBRACE,
    STATE(38), 1,
      sym_groovy_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1728] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(308), 2,
      anon_sym_RBRACE,
      anon_sym_test,
  [1737] = 3,
    ACTIONS(310), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(102), 1,
      sym_groovy_triple_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1748] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(312), 2,
      anon_sym_RBRACE,
      anon_sym_run,
  [1757] = 3,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
    STATE(104), 1,
      sym_suite_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1768] = 2,
    ACTIONS(316), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1776] = 2,
    ACTIONS(318), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1784] = 2,
    ACTIONS(320), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1792] = 2,
    ACTIONS(322), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1800] = 2,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1808] = 2,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1816] = 2,
    ACTIONS(328), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1824] = 2,
    ACTIONS(330), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1832] = 2,
    ACTIONS(332), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1840] = 2,
    ACTIONS(334), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1848] = 2,
    ACTIONS(336), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1856] = 2,
    ACTIONS(338), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1864] = 2,
    ACTIONS(340), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1872] = 2,
    ACTIONS(342), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1880] = 2,
    ACTIONS(344), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1888] = 2,
    ACTIONS(346), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1896] = 2,
    ACTIONS(348), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1904] = 2,
    ACTIONS(350), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1912] = 2,
    ACTIONS(352), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1920] = 2,
    ACTIONS(354), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1928] = 2,
    ACTIONS(356), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1936] = 2,
    ACTIONS(358), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1944] = 2,
    ACTIONS(360), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1952] = 2,
    ACTIONS(362), 1,
      anon_sym_alias,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1960] = 2,
    ACTIONS(364), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1968] = 2,
    ACTIONS(366), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1976] = 2,
    ACTIONS(368), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1984] = 2,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1992] = 2,
    ACTIONS(372), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 126,
  [SMALL_STATE(5)] = 175,
  [SMALL_STATE(6)] = 197,
  [SMALL_STATE(7)] = 219,
  [SMALL_STATE(8)] = 241,
  [SMALL_STATE(9)] = 263,
  [SMALL_STATE(10)] = 285,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 327,
  [SMALL_STATE(13)] = 348,
  [SMALL_STATE(14)] = 383,
  [SMALL_STATE(15)] = 418,
  [SMALL_STATE(16)] = 439,
  [SMALL_STATE(17)] = 460,
  [SMALL_STATE(18)] = 495,
  [SMALL_STATE(19)] = 516,
  [SMALL_STATE(20)] = 535,
  [SMALL_STATE(21)] = 554,
  [SMALL_STATE(22)] = 573,
  [SMALL_STATE(23)] = 592,
  [SMALL_STATE(24)] = 611,
  [SMALL_STATE(25)] = 639,
  [SMALL_STATE(26)] = 667,
  [SMALL_STATE(27)] = 695,
  [SMALL_STATE(28)] = 724,
  [SMALL_STATE(29)] = 741,
  [SMALL_STATE(30)] = 770,
  [SMALL_STATE(31)] = 799,
  [SMALL_STATE(32)] = 828,
  [SMALL_STATE(33)] = 845,
  [SMALL_STATE(34)] = 874,
  [SMALL_STATE(35)] = 889,
  [SMALL_STATE(36)] = 904,
  [SMALL_STATE(37)] = 926,
  [SMALL_STATE(38)] = 940,
  [SMALL_STATE(39)] = 954,
  [SMALL_STATE(40)] = 968,
  [SMALL_STATE(41)] = 982,
  [SMALL_STATE(42)] = 1001,
  [SMALL_STATE(43)] = 1019,
  [SMALL_STATE(44)] = 1037,
  [SMALL_STATE(45)] = 1055,
  [SMALL_STATE(46)] = 1073,
  [SMALL_STATE(47)] = 1091,
  [SMALL_STATE(48)] = 1109,
  [SMALL_STATE(49)] = 1127,
  [SMALL_STATE(50)] = 1145,
  [SMALL_STATE(51)] = 1163,
  [SMALL_STATE(52)] = 1181,
  [SMALL_STATE(53)] = 1199,
  [SMALL_STATE(54)] = 1217,
  [SMALL_STATE(55)] = 1235,
  [SMALL_STATE(56)] = 1253,
  [SMALL_STATE(57)] = 1271,
  [SMALL_STATE(58)] = 1283,
  [SMALL_STATE(59)] = 1301,
  [SMALL_STATE(60)] = 1319,
  [SMALL_STATE(61)] = 1331,
  [SMALL_STATE(62)] = 1349,
  [SMALL_STATE(63)] = 1367,
  [SMALL_STATE(64)] = 1379,
  [SMALL_STATE(65)] = 1391,
  [SMALL_STATE(66)] = 1403,
  [SMALL_STATE(67)] = 1415,
  [SMALL_STATE(68)] = 1427,
  [SMALL_STATE(69)] = 1444,
  [SMALL_STATE(70)] = 1461,
  [SMALL_STATE(71)] = 1472,
  [SMALL_STATE(72)] = 1489,
  [SMALL_STATE(73)] = 1504,
  [SMALL_STATE(74)] = 1521,
  [SMALL_STATE(75)] = 1536,
  [SMALL_STATE(76)] = 1553,
  [SMALL_STATE(77)] = 1568,
  [SMALL_STATE(78)] = 1585,
  [SMALL_STATE(79)] = 1602,
  [SMALL_STATE(80)] = 1619,
  [SMALL_STATE(81)] = 1636,
  [SMALL_STATE(82)] = 1653,
  [SMALL_STATE(83)] = 1663,
  [SMALL_STATE(84)] = 1677,
  [SMALL_STATE(85)] = 1688,
  [SMALL_STATE(86)] = 1697,
  [SMALL_STATE(87)] = 1706,
  [SMALL_STATE(88)] = 1717,
  [SMALL_STATE(89)] = 1728,
  [SMALL_STATE(90)] = 1737,
  [SMALL_STATE(91)] = 1748,
  [SMALL_STATE(92)] = 1757,
  [SMALL_STATE(93)] = 1768,
  [SMALL_STATE(94)] = 1776,
  [SMALL_STATE(95)] = 1784,
  [SMALL_STATE(96)] = 1792,
  [SMALL_STATE(97)] = 1800,
  [SMALL_STATE(98)] = 1808,
  [SMALL_STATE(99)] = 1816,
  [SMALL_STATE(100)] = 1824,
  [SMALL_STATE(101)] = 1832,
  [SMALL_STATE(102)] = 1840,
  [SMALL_STATE(103)] = 1848,
  [SMALL_STATE(104)] = 1856,
  [SMALL_STATE(105)] = 1864,
  [SMALL_STATE(106)] = 1872,
  [SMALL_STATE(107)] = 1880,
  [SMALL_STATE(108)] = 1888,
  [SMALL_STATE(109)] = 1896,
  [SMALL_STATE(110)] = 1904,
  [SMALL_STATE(111)] = 1912,
  [SMALL_STATE(112)] = 1920,
  [SMALL_STATE(113)] = 1928,
  [SMALL_STATE(114)] = 1936,
  [SMALL_STATE(115)] = 1944,
  [SMALL_STATE(116)] = 1952,
  [SMALL_STATE(117)] = 1960,
  [SMALL_STATE(118)] = 1968,
  [SMALL_STATE(119)] = 1976,
  [SMALL_STATE(120)] = 1984,
  [SMALL_STATE(121)] = 1992,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options_stmt, 2, 0, 2),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_stmt, 2, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_identifier, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_stmt, 2, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_identifier, 3, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_identifier, 3, 0, 4),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_stmt, 2, 0, 2),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_stmt, 2, 0, 2),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_declaration, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_stmt, 2, 0, 2),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_profile_stmt, 2, 0, 2),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_run_block_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_run_block_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_run_block_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_run_block_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_block, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_block, 3, 0, 6),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setup_block, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setup_block, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_invocation, 4, 0, 7),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_then_block, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_block, 4, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_block, 5, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setup_block_repeat1, 2, 0, 0),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setup_block_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat2, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat2, 2, 0, 0), SHIFT_REPEAT(120),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_block, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_block, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_string, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_string, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_string, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_string, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0),
  [233] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [236] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params_block, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [267] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_groovy_triple_string_repeat1, 2, 0, 0),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_triple_string_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [283] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_invocable_unit, 1, 0, 0),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_block, 3, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 3, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 4, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_block, 4, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_header, 8, 0, 8),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [324] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 5, 0, 0),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite, 2, 0, 1),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_triple_string, 2, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 3, 0, 0),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [350] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_triple_string, 3, 0, 6),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 2, 0, 0),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_header, 4, 0, 3),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [364] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_header, 4, 0, 5),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [372] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nftest(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nftest",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
