/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 114
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 76
#define ALIAS_COUNT 0
#define TOKEN_COUNT 37
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_nextflow_process = 2,
  anon_sym_nextflow_workflow = 3,
  anon_sym_nextflow_pipeline = 4,
  anon_sym_nextflow_function = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_setup = 8,
  anon_sym_run = 9,
  anon_sym_LPAREN = 10,
  anon_sym_COMMA = 11,
  anon_sym_alias = 12,
  anon_sym_COLON = 13,
  anon_sym_RPAREN = 14,
  anon_sym_test = 15,
  anon_sym_when = 16,
  anon_sym_params = 17,
  anon_sym_then = 18,
  anon_sym_tag = 19,
  anon_sym_script = 20,
  anon_sym_options = 21,
  anon_sym_config = 22,
  anon_sym_name = 23,
  anon_sym_profile = 24,
  sym_groovy_code = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_double_string_token1 = 27,
  anon_sym_SQUOTE = 28,
  aux_sym_single_string_token1 = 29,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 30,
  sym_escape_sequence = 31,
  anon_sym_process = 32,
  anon_sym_workflow = 33,
  anon_sym_function = 34,
  sym_line_comment = 35,
  sym_block_comment = 36,
  sym_source_file = 37,
  sym_suite = 38,
  sym_suite_block = 39,
  sym_setup_block = 40,
  sym_run_block = 41,
  sym_run_header = 42,
  sym_test_block = 43,
  sym_test_header = 44,
  sym_when_block = 45,
  sym_params_block = 46,
  sym_then_block = 47,
  sym_invocation = 48,
  sym_top_level_declaration = 49,
  sym_tag_stmt = 50,
  sym_script_stmt = 51,
  sym_options_stmt = 52,
  sym_config_stmt = 53,
  sym_unit_stmt = 54,
  sym_name_stmt = 55,
  sym_profile_stmt = 56,
  sym_groovy_block = 57,
  sym_brace_block = 58,
  sym_string = 59,
  sym_double_string = 60,
  sym_single_string = 61,
  sym_groovy_triple_string = 62,
  sym_quoted_identifier = 63,
  sym_double_quoted_identifier = 64,
  sym_single_quoted_identifier = 65,
  sym_invocable_unit = 66,
  aux_sym_suite_block_repeat1 = 67,
  aux_sym_suite_block_repeat2 = 68,
  aux_sym_setup_block_repeat1 = 69,
  aux_sym_run_block_repeat1 = 70,
  aux_sym_test_block_repeat1 = 71,
  aux_sym_when_block_repeat1 = 72,
  aux_sym_groovy_block_repeat1 = 73,
  aux_sym_double_string_repeat1 = 74,
  aux_sym_single_string_repeat1 = 75,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_nextflow_process] = "nextflow_process",
  [anon_sym_nextflow_workflow] = "nextflow_workflow",
  [anon_sym_nextflow_pipeline] = "nextflow_pipeline",
  [anon_sym_nextflow_function] = "nextflow_function",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_setup] = "setup",
  [anon_sym_run] = "run",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_alias] = "alias",
  [anon_sym_COLON] = ":",
  [anon_sym_RPAREN] = ")",
  [anon_sym_test] = "test",
  [anon_sym_when] = "when",
  [anon_sym_params] = "params",
  [anon_sym_then] = "then",
  [anon_sym_tag] = "tag",
  [anon_sym_script] = "script",
  [anon_sym_options] = "options",
  [anon_sym_config] = "config",
  [anon_sym_name] = "name",
  [anon_sym_profile] = "profile",
  [sym_groovy_code] = "groovy_code",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_string_token1] = "double_string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_string_token1] = "single_string_token1",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_process] = "process",
  [anon_sym_workflow] = "workflow",
  [anon_sym_function] = "function",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_suite] = "suite",
  [sym_suite_block] = "suite_block",
  [sym_setup_block] = "setup_block",
  [sym_run_block] = "run_block",
  [sym_run_header] = "run_header",
  [sym_test_block] = "test_block",
  [sym_test_header] = "test_header",
  [sym_when_block] = "when_block",
  [sym_params_block] = "params_block",
  [sym_then_block] = "then_block",
  [sym_invocation] = "invocation",
  [sym_top_level_declaration] = "top_level_declaration",
  [sym_tag_stmt] = "tag_stmt",
  [sym_script_stmt] = "script_stmt",
  [sym_options_stmt] = "options_stmt",
  [sym_config_stmt] = "config_stmt",
  [sym_unit_stmt] = "unit_stmt",
  [sym_name_stmt] = "name_stmt",
  [sym_profile_stmt] = "profile_stmt",
  [sym_groovy_block] = "groovy_block",
  [sym_brace_block] = "brace_block",
  [sym_string] = "string",
  [sym_double_string] = "double_string",
  [sym_single_string] = "single_string",
  [sym_groovy_triple_string] = "groovy_triple_string",
  [sym_quoted_identifier] = "quoted_identifier",
  [sym_double_quoted_identifier] = "double_quoted_identifier",
  [sym_single_quoted_identifier] = "single_quoted_identifier",
  [sym_invocable_unit] = "invocable_unit",
  [aux_sym_suite_block_repeat1] = "suite_block_repeat1",
  [aux_sym_suite_block_repeat2] = "suite_block_repeat2",
  [aux_sym_setup_block_repeat1] = "setup_block_repeat1",
  [aux_sym_run_block_repeat1] = "run_block_repeat1",
  [aux_sym_test_block_repeat1] = "test_block_repeat1",
  [aux_sym_when_block_repeat1] = "when_block_repeat1",
  [aux_sym_groovy_block_repeat1] = "groovy_block_repeat1",
  [aux_sym_double_string_repeat1] = "double_string_repeat1",
  [aux_sym_single_string_repeat1] = "single_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_nextflow_process] = anon_sym_nextflow_process,
  [anon_sym_nextflow_workflow] = anon_sym_nextflow_workflow,
  [anon_sym_nextflow_pipeline] = anon_sym_nextflow_pipeline,
  [anon_sym_nextflow_function] = anon_sym_nextflow_function,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_setup] = anon_sym_setup,
  [anon_sym_run] = anon_sym_run,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_alias] = anon_sym_alias,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_test] = anon_sym_test,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_params] = anon_sym_params,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_tag] = anon_sym_tag,
  [anon_sym_script] = anon_sym_script,
  [anon_sym_options] = anon_sym_options,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_name] = anon_sym_name,
  [anon_sym_profile] = anon_sym_profile,
  [sym_groovy_code] = sym_groovy_code,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_string_token1] = aux_sym_double_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_string_token1] = aux_sym_single_string_token1,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_process] = anon_sym_process,
  [anon_sym_workflow] = anon_sym_workflow,
  [anon_sym_function] = anon_sym_function,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_suite] = sym_suite,
  [sym_suite_block] = sym_suite_block,
  [sym_setup_block] = sym_setup_block,
  [sym_run_block] = sym_run_block,
  [sym_run_header] = sym_run_header,
  [sym_test_block] = sym_test_block,
  [sym_test_header] = sym_test_header,
  [sym_when_block] = sym_when_block,
  [sym_params_block] = sym_params_block,
  [sym_then_block] = sym_then_block,
  [sym_invocation] = sym_invocation,
  [sym_top_level_declaration] = sym_top_level_declaration,
  [sym_tag_stmt] = sym_tag_stmt,
  [sym_script_stmt] = sym_script_stmt,
  [sym_options_stmt] = sym_options_stmt,
  [sym_config_stmt] = sym_config_stmt,
  [sym_unit_stmt] = sym_unit_stmt,
  [sym_name_stmt] = sym_name_stmt,
  [sym_profile_stmt] = sym_profile_stmt,
  [sym_groovy_block] = sym_groovy_block,
  [sym_brace_block] = sym_brace_block,
  [sym_string] = sym_string,
  [sym_double_string] = sym_double_string,
  [sym_single_string] = sym_single_string,
  [sym_groovy_triple_string] = sym_groovy_triple_string,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [sym_double_quoted_identifier] = sym_double_quoted_identifier,
  [sym_single_quoted_identifier] = sym_single_quoted_identifier,
  [sym_invocable_unit] = sym_invocable_unit,
  [aux_sym_suite_block_repeat1] = aux_sym_suite_block_repeat1,
  [aux_sym_suite_block_repeat2] = aux_sym_suite_block_repeat2,
  [aux_sym_setup_block_repeat1] = aux_sym_setup_block_repeat1,
  [aux_sym_run_block_repeat1] = aux_sym_run_block_repeat1,
  [aux_sym_test_block_repeat1] = aux_sym_test_block_repeat1,
  [aux_sym_when_block_repeat1] = aux_sym_when_block_repeat1,
  [aux_sym_groovy_block_repeat1] = aux_sym_groovy_block_repeat1,
  [aux_sym_double_string_repeat1] = aux_sym_double_string_repeat1,
  [aux_sym_single_string_repeat1] = aux_sym_single_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_nextflow_process] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nextflow_workflow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nextflow_pipeline] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nextflow_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_setup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_run] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_alias] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_test] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_params] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_script] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_options] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_name] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_profile] = {
    .visible = true,
    .named = false,
  },
  [sym_groovy_code] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_process] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_workflow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_suite] = {
    .visible = true,
    .named = true,
  },
  [sym_suite_block] = {
    .visible = true,
    .named = true,
  },
  [sym_setup_block] = {
    .visible = true,
    .named = true,
  },
  [sym_run_block] = {
    .visible = true,
    .named = true,
  },
  [sym_run_header] = {
    .visible = true,
    .named = true,
  },
  [sym_test_block] = {
    .visible = true,
    .named = true,
  },
  [sym_test_header] = {
    .visible = true,
    .named = true,
  },
  [sym_when_block] = {
    .visible = true,
    .named = true,
  },
  [sym_params_block] = {
    .visible = true,
    .named = true,
  },
  [sym_then_block] = {
    .visible = true,
    .named = true,
  },
  [sym_invocation] = {
    .visible = true,
    .named = true,
  },
  [sym_top_level_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_script_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_options_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_config_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_unit_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_name_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_profile_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_groovy_block] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_string] = {
    .visible = true,
    .named = true,
  },
  [sym_groovy_triple_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_invocable_unit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_suite_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_suite_block_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setup_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_run_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_test_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_when_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_groovy_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_body = 2,
  field_groovy = 3,
  field_identifier = 4,
  field_name = 5,
  field_type = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_body] = "body",
  [field_groovy] = "groovy",
  [field_identifier] = "identifier",
  [field_name] = "name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
  [1] =
    {field_name, 2},
  [2] =
    {field_identifier, 2},
  [3] =
    {field_groovy, 1},
  [4] =
    {field_identifier, 1},
  [5] =
    {field_type, 0},
  [6] =
    {field_alias, 6},
    {field_identifier, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 56,
  [62] = 50,
  [63] = 54,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 72,
  [74] = 71,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 28,
        '\'', 32,
        '(', 15,
        ')', 18,
        ',', 16,
        '/', 7,
        ':', 17,
        '\\', 11,
        '{', 13,
        '}', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '\\') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '{') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(36);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == '{') ADVANCE(13);
      if (lookahead == '}') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(40);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '"') ADVANCE(22);
      if (lookahead == '/') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '"') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '*') ADVANCE(25);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '*') ADVANCE(24);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead == '/') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_groovy_code);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_double_string_token1);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_double_string_token1);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_double_string_token1);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(29);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_single_string_token1);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_single_string_token1);
      if (lookahead == '*') ADVANCE(9);
      if (lookahead == '/') ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_single_string_token1);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(27);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'c', 2,
        'f', 3,
        'n', 4,
        'o', 5,
        'p', 6,
        'r', 7,
        's', 8,
        't', 9,
        'w', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'r') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead == 'h') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == 'x') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 32:
      if (lookahead == 'i') ADVANCE(48);
      END_STATE();
    case 33:
      if (lookahead == 'a') ADVANCE(49);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 'f') ADVANCE(51);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_run);
      END_STATE();
    case 36:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 37:
      if (lookahead == 'u') ADVANCE(53);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_tag);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 42:
      if (lookahead == 'k') ADVANCE(57);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(59);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_name);
      END_STATE();
    case 47:
      if (lookahead == 'f') ADVANCE(61);
      END_STATE();
    case 48:
      if (lookahead == 'o') ADVANCE(62);
      END_STATE();
    case 49:
      if (lookahead == 'm') ADVANCE(63);
      END_STATE();
    case 50:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 52:
      if (lookahead == 'p') ADVANCE(66);
      END_STATE();
    case 53:
      if (lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_test);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 57:
      if (lookahead == 'f') ADVANCE(68);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_alias);
      END_STATE();
    case 59:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(72);
      END_STATE();
    case 63:
      if (lookahead == 's') ADVANCE(73);
      END_STATE();
    case 64:
      if (lookahead == 's') ADVANCE(74);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(75);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_setup);
      END_STATE();
    case 68:
      if (lookahead == 'l') ADVANCE(77);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_config);
      END_STATE();
    case 70:
      if (lookahead == 'o') ADVANCE(78);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(79);
      END_STATE();
    case 72:
      if (lookahead == 's') ADVANCE(80);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_params);
      END_STATE();
    case 74:
      if (lookahead == 's') ADVANCE(81);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_script);
      END_STATE();
    case 77:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(84);
      END_STATE();
    case 79:
      if (lookahead == 'w') ADVANCE(85);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_options);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_process);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_profile);
      END_STATE();
    case 83:
      if (lookahead == 'w') ADVANCE(86);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 85:
      if (lookahead == '_') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_workflow);
      END_STATE();
    case 87:
      if (lookahead == 'f') ADVANCE(88);
      if (lookahead == 'p') ADVANCE(89);
      if (lookahead == 'w') ADVANCE(90);
      END_STATE();
    case 88:
      if (lookahead == 'u') ADVANCE(91);
      END_STATE();
    case 89:
      if (lookahead == 'i') ADVANCE(92);
      if (lookahead == 'r') ADVANCE(93);
      END_STATE();
    case 90:
      if (lookahead == 'o') ADVANCE(94);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(95);
      END_STATE();
    case 92:
      if (lookahead == 'p') ADVANCE(96);
      END_STATE();
    case 93:
      if (lookahead == 'o') ADVANCE(97);
      END_STATE();
    case 94:
      if (lookahead == 'r') ADVANCE(98);
      END_STATE();
    case 95:
      if (lookahead == 'c') ADVANCE(99);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 97:
      if (lookahead == 'c') ADVANCE(101);
      END_STATE();
    case 98:
      if (lookahead == 'k') ADVANCE(102);
      END_STATE();
    case 99:
      if (lookahead == 't') ADVANCE(103);
      END_STATE();
    case 100:
      if (lookahead == 'l') ADVANCE(104);
      END_STATE();
    case 101:
      if (lookahead == 'e') ADVANCE(105);
      END_STATE();
    case 102:
      if (lookahead == 'f') ADVANCE(106);
      END_STATE();
    case 103:
      if (lookahead == 'i') ADVANCE(107);
      END_STATE();
    case 104:
      if (lookahead == 'i') ADVANCE(108);
      END_STATE();
    case 105:
      if (lookahead == 's') ADVANCE(109);
      END_STATE();
    case 106:
      if (lookahead == 'l') ADVANCE(110);
      END_STATE();
    case 107:
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 108:
      if (lookahead == 'n') ADVANCE(112);
      END_STATE();
    case 109:
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 110:
      if (lookahead == 'o') ADVANCE(114);
      END_STATE();
    case 111:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 112:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_nextflow_process);
      END_STATE();
    case 114:
      if (lookahead == 'w') ADVANCE(117);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_nextflow_function);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_nextflow_pipeline);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_nextflow_workflow);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 10},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 10},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 10},
  [63] = {.lex_state = 10},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 10},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 10},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 4},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_nextflow_process] = ACTIONS(1),
    [anon_sym_nextflow_workflow] = ACTIONS(1),
    [anon_sym_nextflow_pipeline] = ACTIONS(1),
    [anon_sym_nextflow_function] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_setup] = ACTIONS(1),
    [anon_sym_run] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_alias] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_test] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_params] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_tag] = ACTIONS(1),
    [anon_sym_script] = ACTIONS(1),
    [anon_sym_options] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_name] = ACTIONS(1),
    [anon_sym_profile] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_process] = ACTIONS(1),
    [anon_sym_workflow] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(102),
    [sym_suite] = STATE(113),
    [anon_sym_nextflow_process] = ACTIONS(5),
    [anon_sym_nextflow_workflow] = ACTIONS(5),
    [anon_sym_nextflow_pipeline] = ACTIONS(5),
    [anon_sym_nextflow_function] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(15), 1,
      anon_sym_script,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(21), 1,
      anon_sym_name,
    ACTIONS(23), 1,
      anon_sym_profile,
    STATE(41), 1,
      sym_setup_block,
    STATE(43), 1,
      sym_invocable_unit,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 2,
      sym_top_level_declaration,
      aux_sym_suite_block_repeat1,
    STATE(45), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(18), 7,
      sym_tag_stmt,
      sym_script_stmt,
      sym_options_stmt,
      sym_config_stmt,
      sym_unit_stmt,
      sym_name_stmt,
      sym_profile_stmt,
  [63] = 17,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(15), 1,
      anon_sym_script,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(21), 1,
      anon_sym_name,
    ACTIONS(23), 1,
      anon_sym_profile,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(36), 1,
      sym_setup_block,
    STATE(43), 1,
      sym_invocable_unit,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 2,
      sym_top_level_declaration,
      aux_sym_suite_block_repeat1,
    STATE(60), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(18), 7,
      sym_tag_stmt,
      sym_script_stmt,
      sym_options_stmt,
      sym_config_stmt,
      sym_unit_stmt,
      sym_name_stmt,
      sym_profile_stmt,
  [126] = 12,
    ACTIONS(31), 1,
      anon_sym_tag,
    ACTIONS(34), 1,
      anon_sym_script,
    ACTIONS(37), 1,
      anon_sym_options,
    ACTIONS(40), 1,
      anon_sym_config,
    ACTIONS(43), 1,
      anon_sym_name,
    ACTIONS(46), 1,
      anon_sym_profile,
    STATE(43), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 2,
      sym_top_level_declaration,
      aux_sym_suite_block_repeat1,
    ACTIONS(29), 3,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
    ACTIONS(49), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(18), 7,
      sym_tag_stmt,
      sym_script_stmt,
      sym_options_stmt,
      sym_config_stmt,
      sym_unit_stmt,
      sym_name_stmt,
      sym_profile_stmt,
  [175] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(52), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [197] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(54), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [219] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(56), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [241] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(58), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [263] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(60), 15,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_RPAREN,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [285] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(62), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [306] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(64), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [327] = 9,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    ACTIONS(68), 1,
      anon_sym_when,
    ACTIONS(70), 1,
      anon_sym_then,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(15), 7,
      sym_setup_block,
      sym_when_block,
      sym_then_block,
      sym_tag_stmt,
      sym_options_stmt,
      sym_config_stmt,
      aux_sym_test_block_repeat1,
  [362] = 9,
    ACTIONS(9), 1,
      anon_sym_setup,
    ACTIONS(13), 1,
      anon_sym_tag,
    ACTIONS(17), 1,
      anon_sym_options,
    ACTIONS(19), 1,
      anon_sym_config,
    ACTIONS(68), 1,
      anon_sym_when,
    ACTIONS(70), 1,
      anon_sym_then,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(12), 7,
      sym_setup_block,
      sym_when_block,
      sym_then_block,
      sym_tag_stmt,
      sym_options_stmt,
      sym_config_stmt,
      aux_sym_test_block_repeat1,
  [397] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(74), 14,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [418] = 9,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(78), 1,
      anon_sym_setup,
    ACTIONS(81), 1,
      anon_sym_when,
    ACTIONS(84), 1,
      anon_sym_then,
    ACTIONS(87), 1,
      anon_sym_tag,
    ACTIONS(90), 1,
      anon_sym_options,
    ACTIONS(93), 1,
      anon_sym_config,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(15), 7,
      sym_setup_block,
      sym_when_block,
      sym_then_block,
      sym_tag_stmt,
      sym_options_stmt,
      sym_config_stmt,
      aux_sym_test_block_repeat1,
  [453] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(96), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [472] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(98), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [491] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(100), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [510] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(102), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [529] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(104), 12,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_tag,
      anon_sym_script,
      anon_sym_options,
      anon_sym_config,
      anon_sym_name,
      anon_sym_profile,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [548] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(106), 11,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_params,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [566] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 11,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_params,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [584] = 6,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    ACTIONS(112), 1,
      anon_sym_params,
    STATE(96), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(115), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(23), 3,
      sym_params_block,
      sym_invocation,
      aux_sym_when_block_repeat1,
  [608] = 6,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    ACTIONS(120), 1,
      anon_sym_params,
    STATE(96), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(23), 3,
      sym_params_block,
      sym_invocation,
      aux_sym_when_block_repeat1,
  [632] = 6,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(124), 1,
      anon_sym_script,
    STATE(96), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(25), 3,
      sym_invocation,
      sym_script_stmt,
      aux_sym_run_block_repeat1,
  [656] = 6,
    ACTIONS(15), 1,
      anon_sym_script,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    STATE(96), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(25), 3,
      sym_invocation,
      sym_script_stmt,
      aux_sym_run_block_repeat1,
  [680] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(132), 8,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [695] = 5,
    ACTIONS(15), 1,
      anon_sym_script,
    STATE(96), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(26), 3,
      sym_invocation,
      sym_script_stmt,
      aux_sym_run_block_repeat1,
  [716] = 5,
    ACTIONS(120), 1,
      anon_sym_params,
    STATE(96), 1,
      sym_invocable_unit,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(25), 3,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
    STATE(24), 3,
      sym_params_block,
      sym_invocation,
      aux_sym_when_block_repeat1,
  [737] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 8,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_test,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [752] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(136), 7,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [766] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(138), 7,
      anon_sym_RBRACE,
      anon_sym_setup,
      anon_sym_when,
      anon_sym_then,
      anon_sym_tag,
      anon_sym_options,
      anon_sym_config,
  [780] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 6,
      anon_sym_RBRACE,
      anon_sym_params,
      anon_sym_script,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [793] = 5,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(144), 1,
      anon_sym_SQUOTE,
    STATE(83), 1,
      sym_quoted_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(81), 2,
      sym_double_quoted_identifier,
      sym_single_quoted_identifier,
  [811] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(14), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [829] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(42), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [847] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(17), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [865] = 5,
    ACTIONS(152), 1,
      anon_sym_RBRACE,
    ACTIONS(154), 1,
      anon_sym_test,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(38), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [883] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(20), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [901] = 5,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    ACTIONS(159), 1,
      anon_sym_run,
    STATE(99), 1,
      sym_run_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(44), 2,
      sym_run_block,
      aux_sym_setup_block_repeat1,
  [919] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(60), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [937] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(38), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [955] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(16), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [973] = 5,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    ACTIONS(165), 1,
      anon_sym_run,
    STATE(99), 1,
      sym_run_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(44), 2,
      sym_run_block,
      aux_sym_setup_block_repeat1,
  [991] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(38), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1009] = 5,
    ACTIONS(159), 1,
      anon_sym_run,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(99), 1,
      sym_run_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(40), 2,
      sym_run_block,
      aux_sym_setup_block_repeat1,
  [1027] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(95), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [1045] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(172), 1,
      anon_sym_RBRACE,
    ACTIONS(174), 1,
      sym_groovy_code,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(51), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1063] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(10), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [1081] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(178), 1,
      anon_sym_RBRACE,
    ACTIONS(180), 1,
      sym_groovy_code,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(54), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1099] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    ACTIONS(184), 1,
      sym_groovy_code,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(56), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1117] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(186), 5,
      anon_sym_RBRACE,
      anon_sym_params,
      anon_sym_process,
      anon_sym_workflow,
      anon_sym_function,
  [1129] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(11), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [1147] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(184), 1,
      sym_groovy_code,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(56), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1165] = 5,
    ACTIONS(146), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    STATE(19), 1,
      sym_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(6), 2,
      sym_double_string,
      sym_single_string,
  [1183] = 5,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      sym_groovy_code,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(56), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1201] = 5,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      sym_groovy_code,
    ACTIONS(202), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(59), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1219] = 5,
    ACTIONS(142), 1,
      anon_sym_DQUOTE,
    ACTIONS(144), 1,
      anon_sym_SQUOTE,
    STATE(106), 1,
      sym_quoted_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(81), 2,
      sym_double_quoted_identifier,
      sym_single_quoted_identifier,
  [1237] = 5,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      sym_groovy_code,
    ACTIONS(206), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1255] = 5,
    ACTIONS(11), 1,
      anon_sym_test,
    ACTIONS(150), 1,
      anon_sym_RBRACE,
    STATE(97), 1,
      sym_test_header,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(38), 2,
      sym_test_block,
      aux_sym_suite_block_repeat2,
  [1273] = 5,
    ACTIONS(193), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    ACTIONS(211), 1,
      sym_groovy_code,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(61), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1291] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_RBRACE,
    ACTIONS(216), 1,
      sym_groovy_code,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(63), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1309] = 5,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(184), 1,
      sym_groovy_code,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(56), 2,
      sym_brace_block,
      aux_sym_groovy_block_repeat1,
  [1327] = 4,
    ACTIONS(220), 1,
      anon_sym_SQUOTE,
    STATE(69), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(222), 2,
      aux_sym_single_string_token1,
      sym_escape_sequence,
  [1342] = 4,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(226), 2,
      aux_sym_double_string_token1,
      sym_escape_sequence,
  [1357] = 4,
    ACTIONS(229), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(231), 2,
      aux_sym_double_string_token1,
      sym_escape_sequence,
  [1372] = 4,
    ACTIONS(233), 1,
      anon_sym_SQUOTE,
    STATE(67), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(235), 2,
      aux_sym_single_string_token1,
      sym_escape_sequence,
  [1387] = 4,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym_double_string_repeat1,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(240), 2,
      aux_sym_double_string_token1,
      sym_escape_sequence,
  [1402] = 4,
    ACTIONS(242), 1,
      anon_sym_SQUOTE,
    STATE(67), 1,
      aux_sym_single_string_repeat1,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(244), 2,
      aux_sym_single_string_token1,
      sym_escape_sequence,
  [1417] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(246), 3,
      anon_sym_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
  [1427] = 2,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
  [1437] = 2,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(250), 3,
      anon_sym_LBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [1447] = 2,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(250), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_groovy_code,
  [1457] = 2,
    ACTIONS(176), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 3,
      anon_sym_LBRACE,
      sym_groovy_code,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [1467] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(252), 2,
      anon_sym_RBRACE,
      anon_sym_run,
  [1476] = 3,
    ACTIONS(254), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(100), 1,
      sym_groovy_triple_string,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1487] = 3,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_groovy_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1498] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(258), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1507] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(260), 2,
      anon_sym_RBRACE,
      anon_sym_test,
  [1516] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(262), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1525] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(264), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1534] = 3,
    ACTIONS(266), 1,
      anon_sym_LBRACE,
    STATE(101), 1,
      sym_suite_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1545] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1556] = 3,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym_groovy_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1567] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(272), 2,
      anon_sym_RBRACE,
      anon_sym_test,
  [1576] = 2,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1584] = 2,
    ACTIONS(276), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1592] = 2,
    ACTIONS(278), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1600] = 2,
    ACTIONS(280), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1608] = 2,
    ACTIONS(282), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1616] = 2,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1624] = 2,
    ACTIONS(286), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1632] = 2,
    ACTIONS(288), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1640] = 2,
    ACTIONS(290), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1648] = 2,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1656] = 2,
    ACTIONS(294), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1664] = 2,
    ACTIONS(296), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1672] = 2,
    ACTIONS(298), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1680] = 2,
    ACTIONS(300), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1688] = 2,
    ACTIONS(302), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1696] = 2,
    ACTIONS(304), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1704] = 2,
    ACTIONS(306), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1712] = 2,
    ACTIONS(308), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1720] = 2,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1728] = 2,
    ACTIONS(312), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1736] = 2,
    ACTIONS(314), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1744] = 2,
    ACTIONS(316), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1752] = 2,
    ACTIONS(318), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1760] = 2,
    ACTIONS(320), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1768] = 2,
    ACTIONS(322), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1776] = 2,
    ACTIONS(324), 1,
      anon_sym_alias,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1784] = 2,
    ACTIONS(326), 1,
      anon_sym_LBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1792] = 2,
    ACTIONS(328), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 126,
  [SMALL_STATE(5)] = 175,
  [SMALL_STATE(6)] = 197,
  [SMALL_STATE(7)] = 219,
  [SMALL_STATE(8)] = 241,
  [SMALL_STATE(9)] = 263,
  [SMALL_STATE(10)] = 285,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 327,
  [SMALL_STATE(13)] = 362,
  [SMALL_STATE(14)] = 397,
  [SMALL_STATE(15)] = 418,
  [SMALL_STATE(16)] = 453,
  [SMALL_STATE(17)] = 472,
  [SMALL_STATE(18)] = 491,
  [SMALL_STATE(19)] = 510,
  [SMALL_STATE(20)] = 529,
  [SMALL_STATE(21)] = 548,
  [SMALL_STATE(22)] = 566,
  [SMALL_STATE(23)] = 584,
  [SMALL_STATE(24)] = 608,
  [SMALL_STATE(25)] = 632,
  [SMALL_STATE(26)] = 656,
  [SMALL_STATE(27)] = 680,
  [SMALL_STATE(28)] = 695,
  [SMALL_STATE(29)] = 716,
  [SMALL_STATE(30)] = 737,
  [SMALL_STATE(31)] = 752,
  [SMALL_STATE(32)] = 766,
  [SMALL_STATE(33)] = 780,
  [SMALL_STATE(34)] = 793,
  [SMALL_STATE(35)] = 811,
  [SMALL_STATE(36)] = 829,
  [SMALL_STATE(37)] = 847,
  [SMALL_STATE(38)] = 865,
  [SMALL_STATE(39)] = 883,
  [SMALL_STATE(40)] = 901,
  [SMALL_STATE(41)] = 919,
  [SMALL_STATE(42)] = 937,
  [SMALL_STATE(43)] = 955,
  [SMALL_STATE(44)] = 973,
  [SMALL_STATE(45)] = 991,
  [SMALL_STATE(46)] = 1009,
  [SMALL_STATE(47)] = 1027,
  [SMALL_STATE(48)] = 1045,
  [SMALL_STATE(49)] = 1063,
  [SMALL_STATE(50)] = 1081,
  [SMALL_STATE(51)] = 1099,
  [SMALL_STATE(52)] = 1117,
  [SMALL_STATE(53)] = 1129,
  [SMALL_STATE(54)] = 1147,
  [SMALL_STATE(55)] = 1165,
  [SMALL_STATE(56)] = 1183,
  [SMALL_STATE(57)] = 1201,
  [SMALL_STATE(58)] = 1219,
  [SMALL_STATE(59)] = 1237,
  [SMALL_STATE(60)] = 1255,
  [SMALL_STATE(61)] = 1273,
  [SMALL_STATE(62)] = 1291,
  [SMALL_STATE(63)] = 1309,
  [SMALL_STATE(64)] = 1327,
  [SMALL_STATE(65)] = 1342,
  [SMALL_STATE(66)] = 1357,
  [SMALL_STATE(67)] = 1372,
  [SMALL_STATE(68)] = 1387,
  [SMALL_STATE(69)] = 1402,
  [SMALL_STATE(70)] = 1417,
  [SMALL_STATE(71)] = 1427,
  [SMALL_STATE(72)] = 1437,
  [SMALL_STATE(73)] = 1447,
  [SMALL_STATE(74)] = 1457,
  [SMALL_STATE(75)] = 1467,
  [SMALL_STATE(76)] = 1476,
  [SMALL_STATE(77)] = 1487,
  [SMALL_STATE(78)] = 1498,
  [SMALL_STATE(79)] = 1507,
  [SMALL_STATE(80)] = 1516,
  [SMALL_STATE(81)] = 1525,
  [SMALL_STATE(82)] = 1534,
  [SMALL_STATE(83)] = 1545,
  [SMALL_STATE(84)] = 1556,
  [SMALL_STATE(85)] = 1567,
  [SMALL_STATE(86)] = 1576,
  [SMALL_STATE(87)] = 1584,
  [SMALL_STATE(88)] = 1592,
  [SMALL_STATE(89)] = 1600,
  [SMALL_STATE(90)] = 1608,
  [SMALL_STATE(91)] = 1616,
  [SMALL_STATE(92)] = 1624,
  [SMALL_STATE(93)] = 1632,
  [SMALL_STATE(94)] = 1640,
  [SMALL_STATE(95)] = 1648,
  [SMALL_STATE(96)] = 1656,
  [SMALL_STATE(97)] = 1664,
  [SMALL_STATE(98)] = 1672,
  [SMALL_STATE(99)] = 1680,
  [SMALL_STATE(100)] = 1688,
  [SMALL_STATE(101)] = 1696,
  [SMALL_STATE(102)] = 1704,
  [SMALL_STATE(103)] = 1712,
  [SMALL_STATE(104)] = 1720,
  [SMALL_STATE(105)] = 1728,
  [SMALL_STATE(106)] = 1736,
  [SMALL_STATE(107)] = 1744,
  [SMALL_STATE(108)] = 1752,
  [SMALL_STATE(109)] = 1760,
  [SMALL_STATE(110)] = 1768,
  [SMALL_STATE(111)] = 1776,
  [SMALL_STATE(112)] = 1784,
  [SMALL_STATE(113)] = 1792,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_string, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_string, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_options_stmt, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_stmt, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_stmt, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_test_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit_stmt, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name_stmt, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_top_level_declaration, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_stmt, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_profile_stmt, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_block, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_block, 3, 0, 4),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_when_block_repeat1, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_when_block_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_when_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_run_block_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_run_block_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_run_block_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setup_block, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setup_block, 4, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_when_block, 4, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_then_block, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_invocation, 4, 0, 6),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat2, 2, 0, 0),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_suite_block_repeat2, 2, 0, 0), SHIFT_REPEAT(90),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setup_block_repeat1, 2, 0, 0),
  [165] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setup_block_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_params_block, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_groovy_block_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_double_string_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0),
  [235] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_single_string_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_invocable_unit, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_block, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_block, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_block, 4, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quoted_identifier, 3, 0, 5),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 4, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quoted_identifier, 3, 0, 5),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_identifier, 1, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 3, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 3, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_header, 4, 0, 2),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 5, 0, 0),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite, 2, 0, 1),
  [306] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_triple_string, 2, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 2, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite_block, 4, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_groovy_triple_string, 3, 0, 4),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_header, 8, 0, 7),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_run_header, 4, 0, 3),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nftest(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nftest",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
